trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceConnectionName: 'azure-resource-manager-connection'
  backendRG: 'rg-firstresource'
  backendStorage: 'storagergfirst13'
  backendContainer: 'tfstate'
  backendKey: 'terraform.tfstate'

stages:
- stage: Terraform_Plan
  displayName: 'Preview Cloud Changes'
  jobs:
  - job: Plan
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform Runner'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      displayName: 'Initialize Backend'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        backendServiceArm: '$(serviceConnectionName)'
        backendAzureRmResourceGroupName: '$(backendRG)'
        backendAzureRmStorageAccountName: '$(backendStorage)'
        backendAzureRmContainerName: '$(backendContainer)'
        backendAzureRmKey: '$(backendKey)'

    - task: TerraformTaskV4@4
      displayName: 'Create Deployment Blueprint'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        environmentServiceNameAzureRM: '$(serviceConnectionName)'

- stage: Terraform_Apply
  displayName: 'Deploy Live to Azure'
  dependsOn: Terraform_Plan
  condition: succeeded()
  jobs:
  - job: Apply
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform Runner'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      displayName: 'Connect to Backend'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        backendServiceArm: '$(serviceConnectionName)'
        backendAzureRmResourceGroupName: '$(backendRG)'
        backendAzureRmStorageAccountName: '$(backendStorage)'
        backendAzureRmContainerName: '$(backendContainer)'
        backendAzureRmKey: '$(backendKey)'

    - task: TerraformTaskV4@4
      displayName: 'Execute Live Changes'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        environmentServiceNameAzureRM: '$(serviceConnectionName)'
        commandOptions: '-auto-approve'