trigger: - main
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: |
    mkdir $(System.DefaultWorkingDirectory)/out
    echo "<h1>Practice Web App running</h1>" > $(System.DefaultWorkingDirectory)/out/index.html
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/out'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    ArtifactName: 'drop'