trigger: none

resources:
  pipelines:
  - pipeline: buildSource
    source: 'ronitthukral-wq.devopsAssignment'
    trigger:
      branches:
        include:
        - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  svcConnection: 'firstserviceconnection'
  backendRG: 'rg-firstresource'
  backendStorage: 'storagergfirst13'
  appName: 'app-devops-assignment-s1'

steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download Artifacts'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProjectId)'
    pipeline: '$(resources.pipeline.buildSource.pipelineID)'
    runVersion: 'latest'
    artifact: 'drop'
    path: '$(System.ArtifactsDirectory)'

- task: AzureFunctionApp@2
  displayName: 'Deploy Function App'
  inputs:
    connectedServiceNameARM: '$(svcConnection)'
    appType: 'functionAppLinux'
    appName: '$(appName)'
    package: '$(System.ArtifactsDirectory)/app.zip'
    runtimeStack: 'NODE|18'

- task: AzureCLI@2
  displayName: 'TF Destroy — Cleanup Infra'
  inputs:
    azureSubscription: '$(svcConnection)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    addSpnToEnvironment: true
    inlineScript: |
      cd $(System.DefaultWorkingDirectory)/terraform

      export ARM_CLIENT_ID=$servicePrincipalId
      export ARM_CLIENT_SECRET=$servicePrincipalKey
      export ARM_TENANT_ID=$tenantId
      export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

      terraform init \
        -backend-config="resource_group_name=$(backendRG)" \
        -backend-config="storage_account_name=$(backendStorage)" \
        -backend-config="container_name=tfstate" \
        -backend-config="key=scenario1.terraform.tfstate"

      terraform destroy -auto-approve -var="scenario=s1" 