trigger: none

resources:
  pipelines:
  - pipeline: buildSource
    source: 'build-pipeline'
    trigger: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  svcConnection: 'firstserviceconnection'
  backendRG: 'rg-firstresource'
  backendStorage: 'storagergfirst13'
  appName: 'app-devops-assignment'
 
steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download Artifacts'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProjectId)'
    pipeline: '$(resources.pipeline.buildSource.pipelineID)'
    runVersion: 'latest'
    artifact: 'drop'
    path: '$(System.ArtifactsDirectory)'

- task: AzureFunctionApp@2
  displayName: 'Deploy Function App'
  inputs:
    connectedServiceNameARM: '$(svcConnection)'
    appType: 'functionAppLinux'
    appName: '$(appName)'
    package: '$(System.ArtifactsDirectory)/app.zip'
    runtimeStack: 'NODE|18'