trigger: none

resources:
  pipelines:
  - pipeline: buildSource
    source: 'build-pipeline'        # exact name in Azure DevOps portal
    trigger: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    pipeline: buildSource
    artifact: 'drop'
    path: '$(System.ArtifactsDirectory)'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Web App'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'firstserviceconnection'
    appType: 'webAppLinux'
    WebAppName: 'app-devops-assignment'
    Package: '$(System.ArtifactsDirectory)/app.zip'
    StartupCommand: 'npx serve -s /home/site/wwwroot -l 8080'