trigger: none

resources:
  pipelines:
  - pipeline: tfSource
    source: 'tf-pipeline-s1' # Name of Infrastructure pipeline in UI Portal
    trigger: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    mkdir -p $(System.DefaultWorkingDirectory)/out
    cp $(System.DefaultWorkingDirectory)/host.json $(System.DefaultWorkingDirectory)/out/ || true
    cp $(System.DefaultWorkingDirectory)/src/package.json $(System.DefaultWorkingDirectory)/out/ || true
    mkdir -p $(System.DefaultWorkingDirectory)/out/HttpTrigger
    cp $(System.DefaultWorkingDirectory)/src/HttpTrigger/function.json $(System.DefaultWorkingDirectory)/out/HttpTrigger/ || true
    cp $(System.DefaultWorkingDirectory)/src/HttpTrigger/index.js $(System.DefaultWorkingDirectory)/out/HttpTrigger/ || true
  displayName: 'Staging Code Artifacts'

- task: ArchiveFiles@2
  displayName: 'Zip Artifacts'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/out'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'