trigger: - main
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformCLI@1
  displayName: 'TF Init'
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    backendType: 'azurerm'
    backendServiceArm: 'azure-practice-connection'
    backendAzureRmResourceGroupName: 'rg-tf-backend-practice'
    backendAzureRmStorageAccountName: 'storagergfirst13'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'modular.terraform.tfstate'
- task: TerraformCLI@1
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    environmentServiceName: 'azure-practice-connection'